# Generated by Django 4.2 on 2023-04-23 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0007_alter_enrollment_price_alter_membershipplan_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                ("workout", models.CharField(max_length=25)),
                ("gender", models.CharField(max_length=25)),
                ("Date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
