# Generated by Django 4.2 on 2023-04-23 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0008_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="appointment")),
                ("timeStamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                ("workout", models.CharField(default="tricep", max_length=25)),
                ("gender", models.CharField(max_length=25)),
                ("Date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(name="Gallery",),
        migrations.DeleteModel(name="Student",),
    ]
