# Generated by Django 4.2 on 2023-04-26 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0009_appointment_user_delete_gallery_delete_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="BMI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
